POST https://us-central1-zottig-planer.cloudfunctions.net/app/eventtemplates
Content-Type: application/json


{
  "category": "testCategory",
  "name": "test1",
  "weight": 150,
  "durationInMinutes": 100,
  "weights": [{"category": "testCategory", "weight": 23}],
  "postProcessing": ""
}

############

GET https://us-central1-zottig-planer.cloudfunctions.net/app/eventtemplates?category=testCategory
Authorization: Bearer 
